# Generated by Django 4.2.7 on 2023-11-02 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
    ]
